import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from '../../providers'; // Da root (my-app/providers.js)
import { MetaMaskProvider } from './components/MetaMaskProvider';  // <-- Aggiunto: Relativo a src/app/components

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "pdb vibemarketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <MetaMaskProvider>  {/* <-- Aggiunto: Wrap per SDK client-side */}
            {children}
          </MetaMaskProvider>
        </Providers>
      </body>
    </html>
  );
}
