import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from '../../providers'; // Da root (my-app/providers.js)

const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://poorlydrawnbinders.vercel.app';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "pdb vibemarketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>
        {/* Nuovo: Meta per Farcaster Mini App (discovery e launch) */}
        <meta name="fc:miniapp" content={JSON.stringify({
          version: '1',
          imageUrl: `${appUrl}/pdb.png`,  // Usa la tua immagine preview
          button: {
            title: 'Launch Poorly Drawn Binders',
            action: {
              type: 'launch_frame',
              name: 'Poorly drawn binders',
              url: `${appUrl}/`,  // Apri home nel modal
              splashImageUrl: `${appUrl}/welcome.png`,
              splashBackgroundColor: '#000000',  // Nero per dark theme
            },
          },
        })} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
